# This is a very basic dockerfile.
# Build
# docker build -t example/nmaptest:1.0 .
#
# Use
# docker run example/nmaptest:1.0 nmap 192.168.1.1

FROM alpine:latest
RUN apk update && apk add nmap

CMD [ "nmap","-h" ]

