# Simplified Filebeat 9.x configuration using filestream inputs
filebeat.inputs:
# Primary catch-all input for all log files in evidence directory
- type: filestream
  id: evidence-logs
  enabled: true
  paths:
    - /evidence/*.log
    - /evidence/*log*
    - /evidence/syslog*
    - /evidence/messages*
    - /evidence/secure*
    - /evidence/auth.log*
    - /evidence/audit.log*
    - /evidence/access.log*
    - /evidence/access_log*
    - /evidence/error.log*
    - /evidence/error_log*
    - /evidence/dmesg*
    - /evidence/journal*.log*
    - /evidence/systemd*.log*
    - /evidence/var/log/**/*.log*
    - /evidence/var/log/syslog*
    - /evidence/var/log/messages*
    - /evidence/var/log/secure*
    - /evidence/var/log/auth.log*
    - /evidence/var/log/audit/audit.log*
    - /evidence/var/log/apache*/*.log*
    - /evidence/var/log/httpd/*.log*
  exclude_files: ['\.gz$', '\.zip$', '\.tar$', '\.bz2$', '\.xz$']
  fields:
    log_type: forensic
    evidence_source: "manual_upload"
  fields_under_root: true
  close_inactive: 5m
  ignore_older: 72h

# Secondary input for any other files in evidence directory
- type: filestream  
  id: evidence-misc
  enabled: true
  paths:
    - /evidence/*
  exclude_files: ['\.gz$', '\.zip$', '\.tar$', '\.bz2$', '\.xz$', '\.log$']
  fields:
    log_type: misc_evidence
    evidence_source: "manual_upload"  
  fields_under_root: true
  close_inactive: 5m
  ignore_older: 72h

processors:
# Extract timestamp from log message and parse various formats
- script:
    lang: javascript
    source: >
      function process(event) {
        var message = event.Get("message");
        if (!message) return;
        
        // Patterns for different log formats
        var patterns = [
          // ISO format: 2025-07-23T16:01:48.376244+01:00
          {regex: /(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:[+-]\d{2}:\d{2}|Z)?)/,
           format: "timestamp_iso"},
          // Syslog format: Aug 20 17:45:01 or Jul 23 16:01:48
          {regex: /(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+(\d{1,2})\s+(\d{2}:\d{2}:\d{2})/,
           format: "timestamp_syslog"},
          // Apache format: [20/Aug/2025:17:45:08 +0000]
          {regex: /\[(\d{2}\/\w{3}\/\d{4}:\d{2}:\d{2}:\d{2}\s+[+-]\d{4})\]/,
           format: "timestamp_apache"},
          // RFC3339: 2025-08-20 17:45:01
          {regex: /(\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2})/,
           format: "timestamp_rfc3339"}
        ];
        
        for (var i = 0; i < patterns.length; i++) {
          var match = message.match(patterns[i].regex);
          if (match) {
            event.Put("extracted_timestamp", match[1] || match[0]);
            event.Put("timestamp_format", patterns[i].format);
            break;
          }
        }
      }

# Parse the extracted timestamp into proper @timestamp
- timestamp:
    field: "extracted_timestamp"
    layouts:
      - '2006-01-02T15:04:05.000000-07:00'  # ISO with microseconds and timezone
      - '2006-01-02T15:04:05.000000+07:00'
      - '2006-01-02T15:04:05.000-07:00'     # ISO with milliseconds
      - '2006-01-02T15:04:05.000+07:00'
      - '2006-01-02T15:04:05-07:00'        # ISO with timezone
      - '2006-01-02T15:04:05+07:00'
      - '2006-01-02T15:04:05Z'             # ISO UTC
      - '2006-01-02T15:04:05'              # ISO without timezone
      - '2006-01-02 15:04:05'              # RFC3339 style
      - 'Jan _2 15:04:05'                  # Syslog format
      - 'Jan 02 15:04:05'                  # Syslog format
      - '02/Jan/2006:15:04:05 -0700'       # Apache format
    target_field: "@timestamp"
    ignore_failure: false

# Add metadata
- add_host_metadata:
    when.not.contains.tags: forwarded
- add_docker_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "forensics-logs-%{+yyyy.MM.dd}"
  pipeline: "forensics-timestamp-parser"
  template.name: "forensics-logs"
  template.pattern: "forensics-logs-*"
  template.settings:
    index.number_of_shards: 1
    index.number_of_replicas: 0
  # Disable data streams to use traditional indices
  allow_older_versions: true

setup.kibana:
  host: "kibana:5601"

setup.template.enabled: true
setup.template.name: "forensics-logs"
setup.template.pattern: "forensics-logs-*"

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644