# Simplified Filebeat 9.x configuration using filestream inputs
filebeat.inputs:
# Primary catch-all input for all log files in evidence directory
- type: filestream
  id: evidence-logs
  enabled: true
  paths:
    - /evidence/*.log
    - /evidence/*log*
    - /evidence/syslog*
    - /evidence/messages*
    - /evidence/secure*
    - /evidence/auth.log*
    - /evidence/audit.log*
    - /evidence/access.log*
    - /evidence/access_log*
    - /evidence/error.log*
    - /evidence/error_log*
    - /evidence/dmesg*
    - /evidence/journal*.log*
    - /evidence/systemd*.log*
    - /evidence/var/log/**/*.log*
    - /evidence/var/log/syslog*
    - /evidence/var/log/messages*
    - /evidence/var/log/secure*
    - /evidence/var/log/auth.log*
    - /evidence/var/log/audit/audit.log*
    - /evidence/var/log/apache*/*.log*
    - /evidence/var/log/httpd/*.log*
  exclude_files: ['\.gz$', '\.zip$', '\.tar$', '\.bz2$', '\.xz$']
  fields:
    log_type: forensic
    evidence_source: "manual_upload"
  fields_under_root: true
  close_inactive: 5m
  ignore_older: 72h

# Secondary input for any other files in evidence directory
- type: filestream  
  id: evidence-misc
  enabled: true
  paths:
    - /evidence/*
  exclude_files: ['\.gz$', '\.zip$', '\.tar$', '\.bz2$', '\.xz$', '\.log$']
  fields:
    log_type: misc_evidence
    evidence_source: "manual_upload"  
  fields_under_root: true
  close_inactive: 5m
  ignore_older: 72h

processors:
- add_host_metadata:
    when.not.contains.tags: forwarded
- add_docker_metadata: ~
- add_kubernetes_metadata: ~
- timestamp:
    field: "@timestamp"
    layouts:
      - '2006-01-02T15:04:05.000Z'
      - '2006-01-02T15:04:05Z'
      - 'Jan _2 15:04:05'
      - 'Jan 02 15:04:05'
    test:
      - '2023-10-15T14:30:45.123Z'
      - 'Oct 15 14:30:45'

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "forensics-logs-%{+yyyy.MM.dd}"
  template.name: "forensics-logs"
  template.pattern: "forensics-logs-*"
  template.settings:
    index.number_of_shards: 1
    index.number_of_replicas: 0

setup.kibana:
  host: "kibana:5601"

setup.template.enabled: true
setup.template.name: "forensics-logs"
setup.template.pattern: "forensics-logs-*"

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644