version: '3.8'

services:
  malware-analyzer:
    build: .
    container_name: malware-analyzer
    volumes:
      # Mount current directory into container for analysis
      - ./:/analysis:rw
      # Ensure results can be written back to host
      - ./results:/analysis/results:rw
    environment:
      - ANALYSIS_DIR=/analysis
    # Remove container after analysis completes
    restart: "no"
    # Run with appropriate user permissions
    user: "0:0"  # root user to ensure write permissions
    stdin_open: false
    tty: false

# Optional: separate service for building only
  malware-analyzer-build:
    build: .
    container_name: malware-analyzer-build
    profiles:
      - build-only
    command: ["echo", "Build completed successfully"]