#!/usr/bin/env python3

import os
import re
import sys
import subprocess
from datetime import datetime

def run(cmd):
    """Run a shell command and return stdout as text."""
    return subprocess.check_output(cmd, shell=True, text=True)

def run_ok(cmd):
    """Run a command and return True if exit code == 0."""
    return subprocess.call(cmd, shell=True,
                           stdout=subprocess.DEVNULL,
                           stderr=subprocess.DEVNULL) == 0

# This version of the script was generated by copliot.

# -----------------------------
# Argument checking
# -----------------------------
if len(sys.argv) != 3:
    print(f"Usage: {sys.argv[0]} <btrfs_image> <path_in_fs>")
    print(f"Example: {sys.argv[0]} xvdb1_btrfs.img /passwd")
    sys.exit(1)

image = sys.argv[1]
target = sys.argv[2]

# -----------------------------
# Verify image is Btrfs
# -----------------------------
file_out = run(f"file {image}")
if "btrfs" not in file_out.lower():
    print("Error: Not a Btrfs filesystem image.")
    sys.exit(1)

print("[+] Image verified as Btrfs.")

# -----------------------------
# Verify file exists (dry-run restore)
# -----------------------------
regex = f"^{target}$"

if not run_ok(f"btrfs restore -s -D --path-regex '{regex}' {image} /tmp"):
    print(f"Error: File '{target}' not found in image.")
    sys.exit(1)

print(f"[+] File exists in image: {target}")

# -----------------------------
# Extract inode number
# -----------------------------
dump = run(f"btrfs inspect-internal dump-tree {image}")

basename = os.path.basename(target)
inode_pattern = rf"location key \(([0-9]+) INODE_ITEM 0\).*?name: {re.escape(basename)}$"

inode_match = re.search(inode_pattern, dump, re.MULTILINE | re.DOTALL)

if not inode_match:
    print("Error: Could not determine inode.")
    sys.exit(1)

inode = inode_match.group(1)
print(f"[+] Inode: {inode}")

# -----------------------------
# Extract timestamps
# -----------------------------
meta_pattern = rf"item [0-9]+ key \({inode} INODE_ITEM 0\)(.*?)item"
meta_match = re.search(meta_pattern, dump, re.DOTALL)

if not meta_match:
    print("Error: Could not extract metadata.")
    sys.exit(1)

meta = meta_match.group(1)

def extract(field):
    m = re.search(rf"{field}\s+([0-9\.]+)", meta)
    return m.group(1) if m else "N/A"

atime = extract("atime")
mtime = extract("mtime")
ctime = extract("ctime")
otime = extract("otime")

print(f"[+] atime: {atime}")
print(f"[+] mtime: {mtime}")
print(f"[+] ctime: {ctime}")
print(f"[+] otime: {otime} (creation time)")

# -----------------------------
# Restore file
# -----------------------------
ts = int(datetime.now().timestamp())
outdir = f"/tmp/restore_{ts}"
os.makedirs(outdir, exist_ok=True)

run(f"btrfs restore -s --path-regex '{regex}' {image} {outdir}")

print(f"[+] File restored to: {outdir}/{basename}")
print("[+] Done.")
